package constant

const (
	CURRENCY_CODE_ALL = "ALL"

	CURRENCY_CODE_USD = "USD"

	CURRENCY_CODE_LINE_POINT = "LINE_POINT"

	CURRENCY_CODE_USDT = "USDT"
	CURRENCY_CODE_KAIA = "KAIA"
	CURRENCY_CODE_BTC  = "BTC"

	CURRENCY_TYPE_FIAT   = 1
	CURRENCY_TYPE_CRYPTO = 2
	CURRENCY_TYPE_POINT  = 3
)
