package status_code

const (
	INVALID_DATE_TIME_FORMAT_CODE    = 8000
	INVALID_DATE_TIME_FORMAT_MESSAGE = "Invalid date time format"

	LOAD_TIMEZONE_LOCATION_ERROR_CODE    = 8001
	LOAD_TIMEZONE_LOCATION_ERROR_MESSAGE = "Error when load timezone location"

	START_TIME_OR_END_TIME_EMPTY_ERROR_CODE    = 8002
	START_TIME_OR_END_TIME_EMPTY_ERROR_MESSAGE = "Start time or end time is empty"

	START_TIME_GREATER_THAN_END_TIME_ERROR_CODE    = 8003
	START_TIME_GREATER_THAN_END_TIME_ERROR_MESSAGE = "Start time can't greater than end time"

	TIME_FILTER_GREATER_THAN_TODAY_ERROR_CODE    = 8004
	TIME_FILTER_GREATER_THAN_TODAY_ERROR_MESSAGE = "Filter time can't greater than today"

	TIME_FILTER_EMPTY_ERROR_CODE    = 8005
	TIME_FILTER_EMPTY_ERROR_MESSAGE = "Time filter is empty"

	DATE_TIME_ERROR_CODE    = 8999
	DATE_TIME_ERROR_MESSAGE = "Date time error"
)
