package status_code

const (
	SUCCESS_CODE    = 1
	SUCCESS_MESSAGE = "Success"

	JSON_SERIALIZE_ERROR_CODE    = 2
	JSON_SERIALIZE_ERROR_MESSAGE = "JSON serialize error"

	JSON_UNSERIALIZE_ERROR_CODE    = 3
	JSON_UNSERIALIZE_ERROR_MESSAGE = "JSON unserialize error"

	QUERY_PARAM_ERROR_CODE    = 4
	QUERY_PARAM_ERROR_MESSAGE = "Failed get query param"

	ENCODE_ERROR_CODE    = 5
	ENCODE_ERROR_MESSAGE = "Encode error"

	DECODE_ERROR_CODE    = 6
	DECODE_ERROR_MESSAGE = "Decode error"

	TYPE_ASSERTION_ERROR_CODE    = 7
	TYPE_ASSERTION_ERROR_MESSAGE = "Type assertion error"

	IO_READ_ERROR_CODE    = 8
	IO_READ_ERROR_MESSAGE = "Failed on IO read"

	IO_COPY_ERROR_CODE    = 9
	IO_COPY_ERROR_MESSAGE = "Failed on IO copy"

	VALIDATION_ERROR_CODE    = 400
	VALIDATION_ERROR_MESSAGE = "Validation error"

	UNAUTHORIZED_ERROR_CODE    = 401
	UNAUTHORIZED_ERROR_MESSAGE = "Invalid JWT token"

	FORBIDDEN_ERROR_CODE    = 403
	FORBIDDEN_ERROR_MESSAGE = "Forbidden"

	DATA_NOT_FOUND_ERROR_CODE    = 404
	DATA_NOT_FOUND_ERROR_MESSAGE = "Data [%s] not found"

	SERVER_ERROR_CODE    = 500
	SERVER_ERROR_MESSAGE = "Server error"

	UNKNOWN_ERROR_CODE    = 999
	UNKNOWN_ERROR_MESSAGE = "Unknown error"
)
