name: Docker Image CI for DEV

on:
  push:
    branches: ["dev"]

env:
  PROJECT_ID: go-api
  REPO_NAME_SCHEDULER: go-scheduler
  REGION: asia-east1
  GAR_LOCATION: asia-east1-docker.pkg.dev/go-api/dev/
  INSTANCE_NAME: go-api-dev-001
  INSTANCE_REGION: asia-east1-b
  IMAGE_NAME: ${{ github.repository }}
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: write # 確保可以觸發 deploy workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GAR_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Extract build parameters
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "REPO_NAME is $REPO_NAME"
          BRANCH_NAME="dev"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "BRANCH_NAME is $BRANCH_NAME"
          COMMIT_HASH=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "COMMIT_HASH is $COMMIT_HASH"
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "TAG_NAME is $TAG_NAME"
          BUILD_DATE="$(TZ=":Asia/Taipei" date '+%Y-%m-%dT%H:%M:%S%z')"
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "BUILD_DATE is $BUILD_DATE"
          BUILD_VERSION=$(git describe --tags --always --dirty)
          echo "BUILD_VERSION=$BUILD_VERSION" >> $GITHUB_ENV
          echo "BUILD_VERSION is $BUILD_VERSION"

      - name: Build image
        run: |
          docker build . --file Dockerfile \
          --target final-api \
          --build-arg TARGET_BUILD=api \
          --build-arg REPO_NAME=${{ env.REPO_NAME }} \
          --build-arg BRANCH_NAME=${{ env.BRANCH_NAME }} \
          --build-arg COMMIT_HASH=${{ env.COMMIT_HASH }} \
          --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
          --build-arg BUILD_VERSION=${{ env.BUILD_VERSION }} \
          --tag ${{ env.GAR_LOCATION }}${{ env.REPO_NAME }}:${{ env.VERSION }}

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}${{ env.REPO_NAME }}:${{ env.VERSION }}

      - name: Build scheduler image
        run: |
          docker build . --file Dockerfile \
          --target final-scheduler \
          --build-arg TARGET_BUILD=scheduler \
          --build-arg REPO_NAME=${{ env.REPO_NAME_SCHEDULER }} \
          --build-arg BRANCH_NAME=${{ env.BRANCH_NAME }} \
          --build-arg COMMIT_HASH=${{ env.COMMIT_HASH }} \
          --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
          --build-arg BUILD_VERSION=${{ env.BUILD_VERSION }} \
          --tag ${{ env.GAR_LOCATION }}${{ env.REPO_NAME_SCHEDULER }}:${{ env.VERSION }}

      - name: Push scheduler image
        run: docker push ${{ env.GAR_LOCATION }}${{ env.REPO_NAME_SCHEDULER }}:${{ env.VERSION }}

      - name: Trigger Deployment Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/docker-image-cd-dev.yml/dispatches \
          -d '{"ref":"dev"}'
